export default () => ({
  port: parseInt(process.env.PORT, 10) || 3000,
  mongoURI: process.env.MONGO_DATABASE_URL,
  NODE_ENV: process.env.NODE_ENV,
  SECRET_ENCRIPTION_ALGORITHM: process.env.SECRET_ENCRIPTION_ALGORITHM,
  SECRET_ENCRIPTION_KEY: process.env.SECRET_ENCRIPTION_KEY,
  WHATSAPP_TOKEN: process.env.WHATSAPP_TOKEN,

   //Email template name
  EMAIL_TEMPLATE_NEW_REGISTRATION:"YABI_WELCOME_TEMPLATE",
  EMAIL_TEMPLATE_ACCOUNT_CONFIRMATION:"YABI_CONFIRM_EMAIL_TEMPLATE",
  EMAIL_TEMPLATE_RESET_PASSWORD:"YABI_RESET_PASSWORD_EMAIL_TEMPLATE",

  //Email Sender
  NO_REPLY_EMAIL_SENDER: "no-reply@yabi.yaba-in.com",
  TEAM_EMAIL_SENDER: "team@yabi.yaba-in.com",

  KEYCLOAK_SERVER_URI: process.env.KEYCLOAK_SERVER_URI,
  KEYCLOAK_SERVER_REALM: process.env.KEYCLOAK_SERVER_REALM,
  KEYCLOAK_SERVER_SECRET:process.env.KEYCLOAK_SERVER_SECRET,
  KEYCLOAK_SERVER_CLIENT_ID:process.env.KEYCLOAK_SERVER_CLIENT_ID

});
